# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

environment:
  matrix:
  - nodejs_version: 6
  - nodejs_version: 8
  - nodejs_version: 10
  - nodejs_version: 12

platform:
  - x86
  - x64

install:
   # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --build-from-source
  - pip install -r requirements.txt

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

deploy_script:
  - scripts\prebuild-publish.bat
